---
- name: Add an Apt signing key
  apt_key:
    url: https://typora.io/linux/public-key.asc
    state: present

- name: Add Typora repository
  apt_repository:
    repo: deb https://typora.io/linux ./

# - name: Add Apt repository
#   command: add-apt-repository 'deb https://typora.io/linux ./'

- name: Install
  apt:
    name: typora
    state: latest
    update_cache: yes

- name: Copy icon
  copy:
    src: icons/typora.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy desktop file
  template:
    src: desktop/typora.desktop
    dest: "/home/{{ username }}/.local/share/applications/typora.desktop"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  template:
    src: dock/typora.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
  with_items:
    - "/home/{{ username }}/.config/Typora/conf/"
    - "/home/{{ username }}/.config/Typora/themes/"

- name: Copy configuration
  copy:
    src: config/typora.conf
    dest: "/home/{{ username }}/.config/Typora/conf/conf.user.json"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Extract themes
  unarchive:
    src: "{{ item }}"
    dest: "/home/{{ username }}/.config/Typora/themes"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
  with_items:
    - config/themes.zip
