---
- name: Install
  snap:
    name: android-studio
    classic: yes
    state: present

- name: Copy config to import manually
  copy:
    src: config/android-studio-config.zip
    dest: "/home/{{ username }}/.config/jetbrains-zip-config/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy desktop file
  template:
    src: desktop/android-studio.desktop
    dest: "/home/{{ username }}/.local/share/applications/android-studio_android-studio.desktop"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  template:
    src: dock/android-studio.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
