---
- name: Install
  snap:
    name: drawio
    state: present

- name: Copy dock item
  template:
    src: dock/draw-io.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy icon
  copy:
    src: icons/draw-io.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy desktop file
  template:
    src: desktop/draw-io.desktop
    dest: "/home/{{ username }}/.local/share/applications/drawio_drawio.desktop"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
