---
- name: Install
  snap:
    name: drawio
    state: present

- name: Copy dock item
  template:
    src: dock/draw-io.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Initialize desktop file
  copy:
    src: /var/lib/snapd/desktop/applications/drawio_drawio.desktop
    dest: "/home/{{ username }}/.local/share/applications"

- name: Add description to desktop file
  replace:
    path: "/home/{{ username }}/.local/share/applications/drawio_drawio.desktop"
    regexp: '^Comment=.*'
    replace: "Comment=Diagram software for making flowcharts, process diagrams, ER and network diagrams."
