---
- name: Add GPG apt Key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Chrome Repository
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    state: present

- name: Install
  apt:
    name: google-chrome-stable
    update_cache: yes

- name: Fix apt source
  lineinfile:
    path: /etc/apt/sources.list.d/google-chrome.list
    regexp: '^.*deb.*$'
    line: "# deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    backrefs: yes
  become: true
  become_user: root

- name: Copy desktop file
  copy:
    src: desktop/google-chrome.desktop
    dest: "/home/{{ username }}/.local/share/applications/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy dock item
  template:
    src: dock/google-chrome.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
