---
- name: Install
  snap:
    name: postman
    state: present

- name: Copy dock item
  template:
    src: dock/postman.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Initialize desktop file
  copy:
    src: /var/lib/snapd/desktop/applications/postman_postman.desktop
    dest: "/home/{{ username }}/.local/share/applications"

- name: Add description to desktop file
  lineinfile:
    path: "/home/{{ username }}/.local/share/applications/postman_postman.desktop"
    line: "Comment=Simplify workflows and create better APIs."
    create: yes