---
- name: Install VLC Player
  snap:
    name: vlc
    state: present

- name: Create VLC Player config directory
  file:
    path: "/home/{{ username }}/.config/vlc"
    state: directory
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: 0755

- name: Configure VLC Player
  copy:
    src: config/vlc.config
    dest: "/home/{{ username }}/.config/vlc/vlcrc"

- name: Copy icon
  copy:
    src: icons/vlc.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Initialize desktop file
  template:
    src: desktop/vlc.desktop
    dest: "/home/{{ username }}/.local/share/applications/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
