---
- name: Install
  snap:
    name: bitwarden
    state: present

- name: Copy icon
  copy:
    src: icons/bitwarden.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy desktop file
  template:
    src: desktop/bitwarden.desktop
    dest: "/home/{{ username }}/.local/share/applications/bitwarden_bitwarden.desktop"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  template:
    src: dock/bitwarden.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
