---
- name: Install.
  apt:
    deb: https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb

- name: Copy desktop file
  copy:
    src: desktop/dbeaver.desktop
    dest: "/home/{{ username }}/.local/share/applications/dbeaver.desktop"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy dock item
  template:
    src: dock/dbeaver.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
