---
- name: Install ZSH
  apt:
    name: zsh
    state: latest

- name: Set as default
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

- name: Install Powerline fonts
  apt:
    name: fonts-powerline
    state: latest

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  become: true
  become_user: "{{ username }}"

- name: Install ZSH autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ username }}/.oh-my-zsh/plugins/zsh-autosuggestions"
  become: true
  become_user: "{{ username }}"

- name: Copy ZSH config
  template:
    src: config/zsh.conf
    dest: "/home/{{ username }}/.zshrc"
    mode: 0644
    owner: "{{ username }}"
    group: "{{ group }}"
