---
- name: Remove default applications
  apt:
    state: absent
    pkg:
        - aisleriot
        - deja-dup
        - gnome-mahjongg
        - gnome-mines
        - gnome-sudoku
        - hplip
        - hplip-data
        - transmission
        - transmission-common
        - transmission-gtk
    purge: yes
    autoclean: yes
    autoremove: yes

# - name: Update system
#   apt:
#     upgrade: full

# - name: Update cache
#   apt:
#     update_cache: true