---
- name: Install
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.2.0-amd64.deb

- name: Initialize desktop file
  copy:
    src: /usr/share/applications/slack.desktop
    dest: "/home/{{ username }}/.local/share/applications"

- name: Copy dock item
  template:
    src: dock/slack.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Add description to desktop file
  replace:
    path: "/home/{{ username }}/.local/share/applications/slack.desktop"
    regexp: '^Comment=.*'
    replace: "Comment=Slack is where work flows."
