---
- name: Install
  snap:
    name: slack
    classic: yes
    state: present

- name: Initialize desktop file
  copy:
    src: /var/lib/snapd/desktop/applications/slack_slack.desktop
    dest: "/home/{{ username }}/.local/share/applications"

- name: Copy dock item
  template:
    src: dock/slack.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
