---
- name: Create 'Applications' directory if it does not exist
  file:
    path: "/home/{{ username }}/Applications"
    state: directory
    mode: '0755'
  become: true
  become_user: "{{ username }}"

- name: Download
  get_url:
    url: "https://dl.getstation.com/download/linux_64?filetype=AppImage"
    dest: "/home/{{ username }}/Applications/Station.AppImage"
  become: true
  become_user: "{{ username }}"

- name: Make executable
  file:
    dest: "/home/{{ username }}/Applications/Station.AppImage"
    mode: a+x