---
- name: Create 'Applications' directory if it does not exist
  file:
    path: "/home/{{ username }}/Applications"
    state: directory
    mode: '0755'
  become: true
  become_user: "{{ username }}"

- name: Download
  get_url:
    url: "https://dl.getstation.com/download/linux_64?filetype=AppImage"
    dest: "/home/{{ username }}/Applications/Station.AppImage"
  become: true
  become_user: "{{ username }}"

- name: Make executable
  file:
    dest: "/home/{{ username }}/Applications/Station.AppImage"
    mode: a+x

- name: Copy icon
  copy:
    src: icons/station.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy desktop file
  template:
    src: desktop/station.desktop
    dest: "/home/{{ username }}/.local/share/applications/station.desktop"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  template:
    src: dock/station.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
