---
- name: Install
  snap:
    name: mailspring
    state: present

- name: Copy dock item
  template:
    src: dock/mailspring.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy icon
  copy:
    src: icons/mailspring.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Initialize desktop file
  template:
    src: desktop/mailspring.desktop
    dest: "/home/{{ username }}/.local/share/applications/mailspring_mailspring.desktop"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
