---
- name: Install
  snap:
    name: intellij-idea-community
    classic: yes
    state: present

- name: Copy config to import manually
  copy:
    src: config/intellij-community-config.zip
    dest: "/home/aleks{{ username }}a/.config/jetbrains-zip-config/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy icon
  copy:
    src: icons/intellij-community.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy desktop file
  template:
    src: desktop/intellij-community.desktop
    dest: "/home/{{ username }}/.local/share/applications/intellij-idea-community_intellij-idea-community.desktop"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  template:
    src: dock/intellij-community.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"