---
- name: Create 'Applications' directory if it does not exist
  file:
    path: "/home/{{ username }}/Applications"
    state: directory
    mode: '0755'
  become: true
  become_user: "{{ username }}"

- name: Download
  get_url:
    url: "https://file.io/BNIMZJeY"
    dest: "/home/{{ username }}/Applications/pCloud.AppImage"
  become: true
  become_user: "{{ username }}"

- name: Make executable
  file:
    dest: "/home/{{ username }}/Applications/pCloud.AppImage"
    mode: a+x

- name: Copy desktop file
  template:
    src: desktop/pcloud.desktop
    dest: "/home/{{ username }}/.local/share/applications/appimagekit-pcloud.desktop"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy dock item
  template:
    src: dock/pcloud.dockitem
    dest: "/home/{{ username }}/.config/plank/dock1/launchers/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"

- name: Copy icon
  copy:
    src: icons/pcloud.png
    dest: "/home/{{ username }}/Documents/Dock/Icons/"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ group }}"
